fs: add mkdirSync and rmdirSync
cgjs/cgjs pull request #21
Opened 2018-04-17 19:58 UTC by sonnyp

2018-04-17 19:59 UTC, sonnyp commented on packages/fs/index.js
> +  const file = Gio.File.new_for_path(path);
I wanted to use GLib for mkdir too but for some reason GLib.mkdir is undefined.

2018-04-17 20:03 UTC, WebReflection requested changes
no need for Gio

2018-04-17 20:03 UTC, WebReflection commented on packages/fs/index.js
> +    throw new Error("failed to make directory");
`failed to make ${path} directory` ?

2018-04-17 20:03 UTC, WebReflection commented on packages/fs/index.js
> +    throw new Error("failed to remove directory");
`failed to remove ${path} directory` ?

2018-04-17 20:03 UTC, WebReflection commented on packages/fs/index.js
> +  const file = Gio.File.new_for_path(path);
how about this? https://developer.gnome.org/glib/stable/glib-File-Utilities.html#g-mkdir

`GLib.mkdir(path, mode)`

2018-04-17 20:03 UTC, WebReflection commented on packages/fs/index.js
> +  if (!ok) {
`if (GLib.mkdir(path, mode) < 0)`

2018-04-17 20:04 UTC, WebReflection commented on packages/fs/index.js
> +  const file = Gio.File.new_for_path(path);
OK, I've read this only now ... which platform are you using ?

2018-04-17 20:07 UTC, WebReflection commented on packages/fs/index.js
> +  const file = Gio.File.new_for_path(path);
`mkdir_with_parents(pathname, mode)` is the exposed method: https://developer.gnome.org/glib/stable/glib-File-Utilities.html#g-mkdir-with-parents

It's the equivalent of `mkdir -p a/b/c` and I think, it's enough for CGJS

When in doubt, `cgjs-about gi.GLib`: https://github.com/cgjs/cgjs-about

2018-04-17 20:26 UTC, sonnyp commented
@WebReflection :speech_balloon: addressed

I'm a bit worried about mkdir_with_parents, the behavior is quite different from Node.js

I already use cgjs-about, very handy :)

2018-04-17 20:38 UTC, WebReflection commented
> I'm a bit worried about mkdir_with_parents, the behavior is quite different from Node.js

since that's the only method we have in GJS, you either file a bug in there and wait for it to be solved, or you use the exposed method that works regardless for everyone that knows the node API.

I am a **very** pragmatic person so guess my pick 😅

2018-04-17 20:39 UTC, merged

2018-04-17 20:54 UTC, WebReflection commented
well done, my _either_ was about moving forward here, not about the need for that method for consistency sake.

But I'm pretty sure they'll answer YAGNI ... or maybe not 😄

2018-04-18 11:16 UTC, sonnyp commented
https://gitlab.gnome.org/GNOME/gobject-introspection/merge_requests/16

2018-04-18 13:32 UTC, WebReflection commented
btw, a proper way to implement async would be using Gio.File indeed. I cannot find anything related to mode in there though  ... how weird